server:
  port: 8080      # Web服务端口

spring:
  application:
    name: vendingMachine
  datasource:
    url: jdbc:mysql://localhost:3306/vending_machine?useSSL=true&serverTimezone=UTC&useUnicode&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rem.vendingmachine.model
  configuration:
    map-underscore-to-camel-case: true