POST http://localhost:8080/api/order/checkout
Content-Type: application/json

{
  "userId": 1,
  "order": [
    { "productId": 1  , "quantity": 1 }
  ]
}

###

GET http://localhost:8080/api/order/details/1
