PUT http://localhost:8080/api/product/update
Content-Type: application/json

{
  "id": 5,
  "name": "天然矿泉水",
  "price": 2.5
}


###

PUT http://localhost:8080/api/product/restock/1?quantity=20
###

GET http://localhost:8080/api/product/all


###

DELETE http://localhost:8080/api/product/delete/1
