POST http://localhost:8080/api/vending-machine-product/1/add-product
Content-Type: application/x-www-form-urlencoded

productId=1&stock=50

###

GET http://localhost:8080/api/vending-machine-product/1/products


###vending_machine_product

DELETE http://localhost:8080/api/vending-machine/delete/1